import time

# --- Mock LLM API Calls ---
# In a real scenario, these would be calls to actual LLM APIs (e.g., Anthropic's Opus/Sonnet).
# We simulate different 'capabilities' and 'costs' here.

def call_llm(model_name, prompt, tokens_to_generate):
    """Simulates an LLM API call."""
    print(f"\nCalling {model_name} with prompt: '{prompt[:50]}...' for {tokens_to_generate} tokens.")
    start_time = time.time()
    # Simulate processing time based on model complexity/capability
    processing_time = (tokens_to_generate / 1000) * (0.5 if 'Opus' in model_name else 0.2) # Opus is 'smarter', takes longer per token but less tokens needed
    time.sleep(processing_time)
    end_time = time.time()
    generated_code = f"# Generated by {model_name}\n# Prompt: {prompt}\nprint('Hello from {model_name}!')\n# ... more code ...\n"
    # Simulate token usage
    input_tokens = len(prompt.split()) # Simple approximation
    output_tokens = tokens_to_generate
    total_tokens = input_tokens + output_tokens
    print(f"{model_name} finished in {end_time - start_time:.2f}s. Used {total_tokens} tokens.")
    return generated_code, total_tokens

# --- Cost Simulation ---
# Define hypothetical costs per million tokens
COST_PER_MILLION_TOKENS = {
    "Opus_5_5": 30.0,  # Higher per-token cost
    "Sonnet_5": 10.0   # Lower per-token cost
}

def calculate_cost(model_name, total_tokens):
    """Calculates the cost of an LLM call."""
    cost_per_token = COST_PER_MILLION_TOKENS[model_name] / 1_000_000
    return total_tokens * cost_per_token

# --- Scenario: Generate a complex function ---
# The core idea: Opus might need fewer tokens to achieve the same result due to better understanding.

complex_prompt = "Write a Python function that takes a list of numbers, filters out even numbers, squares the remaining odd numbers, and returns the sum of these squares. Ensure it handles empty lists gracefully."

# --- Simulation 1: Using Sonnet 5 (lower cost per token, but potentially more tokens needed) ---
print("--- Simulating with Sonnet 5 ---")
# Assume Sonnet 5 needs more 'guidance' or generates more verbose code for this task
# Let's say it uses 1500 tokens (input + output) for this prompt.
socket_tokens_needed = 1500
socket_generated_code, socket_total_tokens = call_llm("Sonnet_5", complex_prompt, socket_tokens_needed)
socket_cost = calculate_cost("Sonnet_5", socket_total_tokens)
print(f"Sonnet 5 Total Tokens: {socket_total_tokens}, Estimated Cost: ${socket_cost:.4f}")

# --- Simulation 2: Using Opus 5.5 (higher cost per token, but potentially fewer tokens needed) ---
print("\n--- Simulating with Opus 5.5 ---")
# Assume Opus 5.5, being more capable, understands the prompt better and generates more concise/efficient code,
# requiring fewer total tokens (e.g., 800 tokens).
opus_tokens_needed = 800
opus_generated_code, opus_total_tokens = call_llm("Opus_5.5", complex_prompt, opus_tokens_needed)
opus_cost = calculate_cost("Opus_5.5", opus_total_tokens)
print(f"Opus 5.5 Total Tokens: {opus_total_tokens}, Estimated Cost: ${opus_cost:.4f}")

# --- Conclusion ---
print("\n--- Cost Comparison ---")
print(f"Sonnet 5 Cost: ${socket_cost:.4f} (Tokens: {socket_total_tokens})")
print(f"Opus 5.5 Cost: ${opus_cost:.4f} (Tokens: {opus_total_tokens})")

if opus_cost < socket_cost:
    print("\nParadox Explained: Although Opus 5.5 has a higher per-token cost, its superior understanding and efficiency led to fewer total tokens being used, resulting in a lower overall cost for this task.")
else:
    print("\nOpus 5.5 was not more economical in this specific simulation.")
